version: "3"
services:
    www:
        build: .
        ports: 
            - "8001:80"
        volumes:
            - ./www:/var/www/html/
            - ./config/php.ini:/usr/local/etc/php/php.ini
        links:
            - db
        networks:
            - default
    db:
        image: mysql:5.7.23
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: familytree
            MYSQL_USER: root
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
        command: --disable-partition-engine-check
        volumes:
            - ./db:/docker-entrypoint-initdb.d
            - persistent:/var/lib/mysql
            - ./config/my.cnf:/etc/my.cnf
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test 
volumes:
    persistent: