<?php
/**
 * Created by PhpStorm.
 * User: robertogiba
 * Date: 28.12.2017
 * Time: 02:28
 */

namespace Controller\Admin\TreeBuilder;


use Controller\Admin\BaseAdminController;
use Database\FamilyManager;
use Model\NewResponse;
use Model\Response;
use Utils\StatusCode;

class MemberListController extends BaseAdminController {
    const userUpdateMemberImagesActions = "user_update_member_images";

    /**
     * @var FamilyManager
     */
    private $manager;

    /**
     * @var MemberEditController
     */
    private $memberEditController;

    /**
     * MemberListController constructor.
     */
    public function __construct()
    {
        $this->manager = new FamilyManager();
        $this->memberEditController = new MemberEditController();
        $this->memberEditController->setManager($this->manager);
        $this->memberEditController->setRemovingEnabled(true);
        $this->memberEditController->setImagesKey(self::userUpdateMemberImagesActions);
    }


    public function action($name, $action, $params)
    {
        parent::action($name, $action, $params); // TODO: Change the autogenerated stub

        switch ($action) {
            case "edit":
                $this->editSelectedMember();
                break;
            case "getMembers":
                if (isset($_GET["id"])) {
                    $this->loadSelectedMember($_GET["id"]);
                } else {
                    $this->loadMembers();
                }
                break;
            case "update":
                if (isset($_GET["id"])) {
                    $this->memberEditController->updateSelectedMember($_GET["id"]);
                }
                break;
            case "upload":
                $this->memberEditController->uploadFiles();
                break;
            case "removeImage":
                $memberId = $_POST["memberId"];
                $this->memberEditController->removeUploadedFile($memberId);
                break;
            case "removeTempImage":
                $this->memberEditController->removeTemporaryUploadedFile();
                break;
            case "removeMember":
                $this->memberEditController->removeMember();
                break;
            default:
                $this->viewIndex();
                break;
        }
    }

    private function viewIndex()
    {
        if (!isset($_SESSION["selectedFamily"])) {
            return;
        }

        $selectedFamily = $this->loadFamilyData($_SESSION["selectedFamily"]);
        $members = $this->manager->loadFamily($selectedFamily->id);

        echo $this->render("/admin/trees/tree_builder_members.html.twig", [
            "userLogged" => $this->userLogged,
            "family" => $selectedFamily,
            "familyMembers" => $members
        ]);
    }

    private function loadFamilyData($familyId)
    {
        $families = $this->manager->loadFamilies();

        $availableFamily = null;
        foreach ($families as $key => $value) {
            if ($value->
                id == $familyId) {
                $availableFamily = $value;
                break;
            }
        }

        return $availableFamily;
    }

    private function editSelectedMember()
    {
        if (!isset($_POST["member"]) || !isset($_SESSION["selectedFamily"])) {
            return;
        }

        $familyMember = $this->manager->getFamilyMemberDetails($_POST["member"]);

        $familyId = $_SESSION["selectedFamily"];
        $members = $this->manager->loadFamily($familyId);
        $possiblePartners = $this->manager->loadPossiblePartners($familyId, intval($familyMember->id));

        $response = array("template" => $this->render("/admin/trees/tree_builder_edit_member.html.twig", [
            "selectedMember" => $familyMember,
            "members" => $members,
            "partners" => $possiblePartners,
            "removingEnabled" => true,
            "imageAction" => "/admin/tree_builder/members/upload"
        ]));
        $this->sendJsonResponse($response);
    }

    private function loadSelectedMember($id)
    {
        $member = $this->manager->getFamilyMemberDetails($id);

        if (is_null($member)) {
            $response = new Response(StatusCode::NOT_FOUND, $this->translate("admin-edit-member-not-found"));
            $this->sendJsonResponse($response);
            return;
        }

        echo $this->sendJsonResponse($member);
    }

    private function loadMembers()
    {
        if (!isset($_SESSION["selectedFamily"])) {
            return;
        }

        $familyId = $_SESSION["selectedFamily"];
        $members = $this->manager->loadFamily($familyId);

        $responseContent = array("template" => $this->render("/admin/trees/tree_builder_members_list.html.twig", [
            "familyMembers" => $members
        ]));

        $response = new NewResponse("", StatusCode::OK);
        $response->setContent($responseContent);

        $this->sendJsonNewResponse($response);
    }
}