<?php
/**
 * Created by PhpStorm.
 * User: robertogiba
 * Date: 28.12.2017
 * Time: 02:28
 */

namespace Controller\Admin\TreeBuilder;


use Controller\Admin\BaseAdminController;
use Database\FamilyManager;
use Model\FamilyMember;

class MemberListController extends BaseAdminController {
    private $manager;

    /**
     * MemberListController constructor.
     */
    public function __construct()
    {
        $this->manager = new FamilyManager();
    }


    public function action($name, $action, $params)
    {
        parent::action($name, $action, $params); // TODO: Change the autogenerated stub

        switch ($action) {
            case "edit":
                $this->editSelectedMember();
                break;
            default:
                $this->viewIndex();
                break;
        }
    }

    private function viewIndex()
    {
        if (!isset($_SESSION["selectedFamily"])) {
            return;
        }

        $selectedFamily = $this->loadFamilyData($_SESSION["selectedFamily"]);
        $members = $this->manager->loadFamily($selectedFamily->id);

        echo $this->render("/admin/trees/tree_builder_members_list.html.twig", [
            "userLogged" => $this->userLogged,
            "family" => $selectedFamily,
            "familyMembers" => $members
        ]);
    }

    private function loadFamilyData($familyId)
    {
        $families = $this->manager->loadFamilies();

        $availableFamily = null;
        foreach ($families as $key => $value) {
            if ($value->
                id == $familyId) {
                $availableFamily = $value;
                break;
            }
        }

        return $availableFamily;
    }

    private function editSelectedMember()
    {
        if (!isset($_POST["member"]) || !isset($_SESSION["selectedFamily"])) {
            return;
        }

        $familyMember = $this->arrayToObject($_POST["member"], FamilyMember::class);

        $familyId = $_SESSION["selectedFamily"];
        $members = $this->manager->loadFamily($familyId);
        $possiblePartners = $this->manager->loadPossiblePartners($familyId, intval($familyMember->id), intval($familyMember->parent));

        $response = array("template" => $this->render("/admin/trees/tree_builder_edit_member.html.twig", [
            "selectedMember" => $familyMember,
            "members" => $members,
            "partners" => $possiblePartners
        ]));
        $this->sendJsonResponse($response);
    }

    private function sendJsonResponse($data)
    {
        header("Content-type: Application/json");
        echo json_encode($data);
    }
}