<?php
/**
 * Created by PhpStorm.
 * User: robertogiba
 * Date: 28.12.2017
 * Time: 02:28
 */

namespace Controller\Admin\TreeBuilder;


use Controller\Admin\BaseAdminController;
use Database\FamilyManager;
use Model\FamilyMember;
use Model\Response;
use Utils\ImageFileHelper;
use Utils\StatusCode;

class MemberListController extends BaseAdminController {
    const userUpdateMemberImagesActions = "user_update_member_images";

    private $manager;
    private $imageFileHelper;

    /**
     * MemberListController constructor.
     */
    public function __construct()
    {
        $this->manager = new FamilyManager();
        $this->imageFileHelper = new ImageFileHelper();
    }


    public function action($name, $action, $params)
    {
        parent::action($name, $action, $params); // TODO: Change the autogenerated stub

        switch ($action) {
            case "edit":
                $this->editSelectedMember();
                break;
            case "getMembers":
                if (isset($_GET["id"])) {
                    $this->loadSelectedMember($_GET["id"]);
                }
                break;
            case "update":
                if (isset($_GET["id"])) {
                    $this->updateSelectedMember($_GET["id"]);
                }
                break;
            case "upload":
                $this->uploadFiles();
                break;
            case "removeImage":
                $memberId = $_POST["memberId"];
                $this->removeUploadedFile($memberId);
                break;
            case "removeTempImage":
                $this->removeTemporaryUploadedFile();
                break;
            default:
                $this->viewIndex();
                break;
        }
    }

    private function viewIndex()
    {
        if (!isset($_SESSION["selectedFamily"])) {
            return;
        }

        $selectedFamily = $this->loadFamilyData($_SESSION["selectedFamily"]);
        $members = $this->manager->loadFamily($selectedFamily->id);

        echo $this->render("/admin/trees/tree_builder_members_list.html.twig", [
            "userLogged" => $this->userLogged,
            "family" => $selectedFamily,
            "familyMembers" => $members
        ]);
    }

    private function loadFamilyData($familyId)
    {
        $families = $this->manager->loadFamilies();

        $availableFamily = null;
        foreach ($families as $key => $value) {
            if ($value->
                id == $familyId) {
                $availableFamily = $value;
                break;
            }
        }

        return $availableFamily;
    }

    private function editSelectedMember()
    {
        if (!isset($_POST["member"]) || !isset($_SESSION["selectedFamily"])) {
            return;
        }

//        $familyMember = $this->arrayToObject($_POST["member"], FamilyMember::class);
        $familyMember = $this->manager->getFamilyMemberDetails($_POST["member"]);

        $familyId = $_SESSION["selectedFamily"];
        $members = $this->manager->loadFamily($familyId);
        $possiblePartners = $this->manager->loadPossiblePartners($familyId, intval($familyMember->id));

        $response = array("template" => $this->render("/admin/trees/tree_builder_edit_member.html.twig", [
            "selectedMember" => $familyMember,
            "members" => $members,
            "partners" => $possiblePartners,
            "imageAction" => "/admin/tree_builder/members/upload"
        ]));
        $this->sendJsonResponse($response);
    }

    private function loadSelectedMember($id)
    {
        $member = $this->manager->getFamilyMemberDetails($id);

        if (is_null($member)) {
            $response = new Response(StatusCode::NOT_FOUND, "Member not found");
            $this->sendJsonResponse($response);
            return;
        }

        echo $this->sendJsonResponse($member);
    }

    private function updateSelectedMember($id)
    {
        if (!isset($_POST["member"])) {
            $response = new Response("Missing parameter member", StatusCode::UNPROCESSED_ENTITY);
            $this->sendJsonResponse($response);
            return;
        }

        $familyMember = $this->arrayToObject($_POST["member"], FamilyMember::class);

        $isUpdated = $this->manager->updateFamilyMember($id, $familyMember);

        $imagesChanged = $this->checkIfImagesChange($id);

        if (!$isUpdated && $imagesChanged) {
            $isUpdated = $imagesChanged;
        }

        $response = null;
        if ($isUpdated) {
            $response = new Response("Member updated", StatusCode::OK);
        } else {
            $response = new Response("No changes", StatusCode::NO_CONTENT);
        }

        $this->sendJsonResponse($response);
    }

    private function checkIfImagesChange($id)
    {
        $filteredFiles = $this->imageFileHelper->checkAction($_SESSION[self::userUpdateMemberImagesActions],
            "uploads", "member_image_");

        $isSucceed = false;

        if (count($filteredFiles->uploaded) > 0) {
            $isSucceed = $this->manager->insertMemberImage($id, $filteredFiles->uploaded);
        }

        if (count($filteredFiles->removed) > 0) {
            $isSucceed = $this->manager->removeMemberImage($id);

            if ($isSucceed) {
                $this->imageFileHelper->removeFiles($filteredFiles->removed);
            }
        }

        $_SESSION[self::userUpdateMemberImagesActions] = [];
        return $isSucceed;
    }

    private function uploadFiles()
    {
        $receivedAction = $this->imageFileHelper->uploadFiles($_FILES, "uploads/temp",
            "member_image_", 90);

        if (!is_null($receivedAction)) {
            $_SESSION[self::userUpdateMemberImagesActions][] = $receivedAction;
        }
    }

    private function removeUploadedFile($id)
    {
        $image = $this->manager->retrieveMemberImage($id);

        if (!is_null($image)) {
            $preparedAction = $this->imageFileHelper->prepareAction($image->image, "remove");

            $_SESSION[self::userUpdateMemberImagesActions][] = $preparedAction;
        }

        $response = new Response("Removing image for: $id", StatusCode::OK);
        $this->sendJsonResponse($response);
    }

    private function removeTemporaryUploadedFile()
    {
        $isSucceed = $this->imageFileHelper->removeTempFiles($_SESSION[self::userUpdateMemberImagesActions]);

//            true;
//
//        foreach ($_SESSION[self::userUpdateMemberImagesActions] as $key => $action) {
//            if ($action->action === "remove") {
//                continue;
//            }
//
//            if (!unlink($action->data)) {
//                $isSucceed = false;
//                break;
//            } else {
//                unset($_SESSION[self::userUpdateMemberImagesActions][$key]);
//            }
//        }

        $response = null;
        if ($isSucceed)
            $response = new Response("Uploaded image removed", StatusCode::OK);
        else
            $response = new Response("Cannot remove image", StatusCode::UNPROCESSED_ENTITY);

        $this->sendJsonResponse($response);
    }

    private function sendJsonResponse($data)
    {
        header("Content-type: Application/json");
        echo json_encode($data);
    }
}